python attribute_classifier/train_classifier.py \
    --pretrained_model gpt2-xl \
    --pool_method last \
    --dataname /home/data/corpora/StanfordSentimentTreebank_PTB/preprocessed_sst5 \
    --num_labels 5 \
    --n_epochs 10 \
    --batch_size 32 \
    --max_length 64 \
    --optimizer adamw \
    --weight_decay 0.01 \
    --lr 5e-5 \
    --linear_scheduler \
    --seed 2022 \
    --verbose \
    --checkpoint_dir saved_models/gpt2-xl-sst5-pool_last-seed2022/
