python attribute_classifier/train_classifier.py \
    --pretrained_model gpt2-xl \
    --pool_method max \
    --dataname sst2 \
    --num_labels 2 \
    --n_epochs 10 \
    --batch_size 32 \
    --max_length 64 \
    --optimizer adamw \
    --weight_decay 0.01 \
    --lr 5e-5 \
    --linear_scheduler \
    --seed 2022 \
    --verbose \
    --checkpoint_dir saved_models/gpt2-xl-sst2-basic-seed2022/
